== About Cojo
* Designing & Coding for the Internet since 1998
* Senior Designoper at DataStax
* Founder of Girl Develop It Boulder/Denver
* hi@cojorado.com
* @cojorado 

== Slides

View these slides online at: http://cara-jo.github.io/teaching-materials/[cara-jo.github.io/teaching-materials/]

== What is Sketch?

* Easy to use digital design tool that is relatively new to the design community
* Affordable alternative to the more expensive Adobe design products
* Vector based tool for visual designers 
* Makes it easy to turn design files into fully functional sites

== What we will be covering in this workshop
* Sketch Interface
* Creating & Moving Shapes
* Layer & Text Styling
* Vectors
* Symbols
* Exporting
* Collaborating
* Tools & Resources

== Downloading Sketch
_Sketch is a Mac OS X only application that requires OS X 10.9 and above._

Sketch offers a free 30 day trial on the Bohemian Coding website.

Go to http://bohemiancoding.com/sketch/[bohemiancoding.com/sketch/] and download the free trial

To purchase the full version you can either buy it on this website or through the Apple App Store

